/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/KenworthTest.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/KenworthTest.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.piece_0064.geometry} material={materials.mat_0012_glass} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_0.geometry} material={materials.mat_0000_details} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_1.geometry} material={materials['plastic.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_10.geometry} material={materials['plastic.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_2.geometry} material={materials['plastic.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_3.geometry} material={materials.oaint_color} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_4.geometry} material={materials['plastic.009']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_5.geometry} material={materials['plastic.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_7.geometry} material={materials['plastic.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_9.geometry} material={materials.mat_0012_glass} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_0001.geometry} material={materials.Chasis} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_1001.geometry} material={materials['plastic.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_3001.geometry} material={materials.mat_0003_details} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_4001.geometry} material={materials['plastic.010']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_5001.geometry} material={materials.mat_0005_floor_dif} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_6001.geometry} material={materials.mat_0006_chrome_base} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_7001.geometry} material={materials['plastic.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_8001.geometry} material={materials['plastic.011']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_0014.geometry} material={materials['Material.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_1014.geometry} material={materials['Material.001']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_2009.geometry} material={materials['Material.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_3010.geometry} material={materials['Material.001']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_4009.geometry} material={materials.tier} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_0017.geometry} material={materials.mat_0000_kenw_rhub_01_c} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_1017.geometry} material={materials['Material.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_4004.geometry} material={materials.tier} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_0008.geometry} material={materials['mat_0000_kenw_rhub_01_c.001']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_1008.geometry} material={materials['Material.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_0010.geometry} material={materials['Material.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_1009.geometry} material={materials['Material.001']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_2001.geometry} material={materials['Material.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_3004.geometry} material={materials['Material.001']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_4006.geometry} material={materials.tier} />
      <mesh geometry={nodes.piece_4005.geometry} material={materials.tier} />
      <mesh geometry={nodes.piece_0013.geometry} material={materials['mat_0000_kenw_rhub_01_c.003']} />
      <mesh geometry={nodes.piece_1013.geometry} material={materials['Material.008']} />
      <mesh geometry={nodes.piece_0009.geometry} material={materials['mat_0000_kenw_rhub_01_c.002']} />
      <mesh geometry={nodes.piece_1010.geometry} material={materials['Material.008']} />
      <mesh geometry={nodes.piece_0012.geometry} material={materials['Material.008']} />
      <mesh geometry={nodes.piece_1012.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.piece_2005.geometry} material={materials['Material.008']} />
      <mesh geometry={nodes.piece_3006.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.piece_0011.geometry} material={materials['Material.008']} />
      <mesh geometry={nodes.piece_1011.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.piece_2004.geometry} material={materials['Material.008']} />
      <mesh geometry={nodes.piece_3005.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.piece_0024.geometry} material={materials['Material.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_1024.geometry} material={materials['Material.001']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_0025.geometry} material={materials['Material.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_2015.geometry} material={materials['Material.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_3016.geometry} material={materials['Material.001']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_0028.geometry} material={materials['plastic.010']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_1028.geometry} material={materials['Material.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_0029.geometry} material={materials.tier} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_5011.geometry} material={materials.tier} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_1030.geometry} material={materials.tier} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_4015.geometry} material={materials.tier} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_0036.geometry} material={materials['plastic.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_1034.geometry} material={materials['plastic.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_10002.geometry} material={materials.mat_0010_decals_c} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_11002.geometry} material={materials['plastic.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_12001.geometry} material={materials['plastic.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_3022.geometry} material={materials['plastic.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_4017.geometry} material={materials['plastic.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_5014.geometry} material={materials['plastic.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_6012.geometry} material={materials['plastic.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_7012.geometry} material={materials['plastic.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_8003.geometry} material={materials['plastic.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_9001.geometry} material={materials['plastic.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_0002.geometry} material={materials.mat_0012_glass} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_1002.geometry} material={materials['mat_0001_cabin_details_difspec.001']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_2002.geometry} material={materials.oaint_color} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_3002.geometry} material={materials['plastic.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_4002.geometry} material={materials['plastic.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_0004.geometry} material={materials['plastic.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_1004.geometry} material={materials['mat_0001_chrome_base.002']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_2006.geometry} material={materials['plastic.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_3007.geometry} material={materials['mat_0003_rivets_difopa.001']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_4003.geometry} material={materials.oaint_color} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_0005.geometry} material={materials['mat_0012_glass.001']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_1005.geometry} material={materials['plastic.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_2007.geometry} material={materials['plastic.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_0015.geometry} material={materials['mat_0000_floor_dif.001']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_1007.geometry} material={materials['plastic.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_0016.geometry} material={materials.oaint_color} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_0026.geometry} material={materials['plastic.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_1015.geometry} material={materials['mat_0000_chrome_base.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_0027.geometry} material={materials['mat_0000_chrome_base.004']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_0030.geometry} material={materials['plastic.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_0032.geometry} material={materials['plastic.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_0038.geometry} material={materials.mat_0000_lamps_front_led_difspec} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_1026.geometry} material={materials['plastic.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_2008.geometry} material={materials.mat_0012_glass} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_3008.geometry} material={materials.mat_0003_chrome_base} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_4007.geometry} material={materials.mat_0000_lamps_front_led_difspec} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_6003.geometry} material={materials.mat_0000_lamps_front_led_difspec} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_0039.geometry} material={materials['mat_0002_chrome_base.001']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_0043.geometry} material={materials['plastic.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_0045.geometry} material={materials.mat_0000_frontgrill_chrome_difopa} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_1036.geometry} material={materials.mat_0001_radiator_difspec} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_2011.geometry} material={materials['mat_0002_chrome_base.001']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_0046.geometry} material={materials['plastic.001']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_1037.geometry} material={materials.oaint_color} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_0047.geometry} material={materials['plastic.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_0048.geometry} material={materials['plastic.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_1038.geometry} material={materials.oaint_color} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_2016.geometry} material={materials['mat_0002_chrome_base.002']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_3011.geometry} material={materials['mat_0003_chrome_base.001']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_4008.geometry} material={materials['plastic.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_0049.geometry} material={materials['plastic.008']} />
      <mesh geometry={nodes.piece_0050.geometry} material={materials.mat_0000_decals_c} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_1040.geometry} material={materials['plastic.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_0051.geometry} material={materials['plastic.009']} />
      <mesh geometry={nodes.piece_1041.geometry} material={materials['plastic.008']} />
      <mesh geometry={nodes.piece_2018.geometry} material={materials['plastic.008']} />
      <mesh geometry={nodes.piece_4010.geometry} material={materials['plastic.008']} />
      <mesh geometry={nodes.piece_7003.geometry} material={materials.mat_0007_lights_r_dif} />
      <mesh geometry={nodes.piece_0052.geometry} material={materials['mat_0002_chrome_base.003']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_2023.geometry} material={materials['mat_0002_chrome_base.003']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_0053.geometry} material={materials['mat_0000_floor_dif.002']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_0054.geometry} material={materials['plastic.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_1044.geometry} material={materials['plastic.009']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_2024.geometry} material={materials['plastic.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_0055.geometry} material={materials['mat_0000_details.001']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_1045.geometry} material={materials.mat_0001_lamps_working_led_difspec} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_2025.geometry} material={materials['plastic.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_3017.geometry} material={materials['plastic.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_4013.geometry} material={materials['plastic.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_5009.geometry} material={materials.oaint_color} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_0056.geometry} material={materials['plastic.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_1046.geometry} material={materials.oaint_color} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_2026.geometry} material={materials['plastic.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_3018.geometry} material={materials['plastic.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_4014.geometry} material={materials['plastic.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_5010.geometry} material={materials['plastic.009']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_0058.geometry} material={materials['plastic.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_1048.geometry} material={materials.mat_0012_glass} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_2028.geometry} material={materials['plastic.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_0059.geometry} material={materials['plastic.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_1049.geometry} material={materials.oaint_color} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_0060.geometry} material={materials['plastic.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_0061.geometry} material={materials['mat_0000_chrome_base.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_1051.geometry} material={materials['plastic.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_0062.geometry} material={materials['plastic.008']} rotation={[2.258, 0, Math.PI]} />
      <mesh geometry={nodes.piece_1052.geometry} material={materials['plastic.008']} rotation={[2.258, 0, Math.PI]} />
      <mesh geometry={nodes.piece_2030.geometry} material={materials['plastic.008']} rotation={[2.258, 0, Math.PI]} />
      <mesh geometry={nodes.piece_3023.geometry} material={materials['plastic.008']} rotation={[2.258, 0, Math.PI]} />
      <mesh geometry={nodes.piece_4020.geometry} material={materials['plastic.008']} rotation={[2.258, 0, Math.PI]} />
      <mesh geometry={nodes.piece_5013.geometry} material={materials.mat_0005_decals_c} rotation={[2.258, 0, Math.PI]} />
      <mesh geometry={nodes.piece_1054.geometry} material={materials.mat_0025_alu_base} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_2032.geometry} material={materials['plastic.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_3025.geometry} material={materials['plastic.010']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_1055.geometry} material={materials['plastic.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_2033.geometry} material={materials['plastic.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_3026.geometry} material={materials.mat_0003_connectors} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_4022.geometry} material={materials.mat_0003_connectors} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_0067.geometry} material={materials['plastic.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_1056.geometry} material={materials['plastic.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_0068.geometry} material={materials['plastic.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_1057.geometry} material={materials['plastic.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_11006.geometry} material={materials['plastic.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_12005.geometry} material={materials['plastic.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_13003.geometry} material={materials['mat_0013_glass_int.003']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_14003.geometry} material={materials['mat_0014_leatherdiamond_beige_c.003']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_15003.geometry} material={materials['plastic.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_16003.geometry} material={materials['plastic.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_17003.geometry} material={materials['plastic.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_18003.geometry} material={materials['mat_0018_bedside_c.003']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_19003.geometry} material={materials['mat_0019_bedpattern01_c.003']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_2035.geometry} material={materials['mat_0002_brushed_aluminium_c.003']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_20003.geometry} material={materials['mat_0020_leatherdiamond_black_c.003']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_21003.geometry} material={materials['plastic.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_22003.geometry} material={materials['plastic.009']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_23003.geometry} material={materials['plastic.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_24004.geometry} material={materials['mat_0024_plastic_beige_c.003']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_25004.geometry} material={materials['plastic.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_26003.geometry} material={materials['mat_0026_leather_beige_c.003']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_27003.geometry} material={materials['mat_0027_wpass.003']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_3027.geometry} material={materials['mat_0003_details_c.003']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_30003.geometry} material={materials['plastic.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_31003.geometry} material={materials.oaint_color} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_32003.geometry} material={materials['mat_0032_plastic_smooth_grey.003']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_33003.geometry} material={materials['plastic.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_34004.geometry} material={materials['plastic.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_35004.geometry} material={materials['mat_0035_decals_c.003']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_36004.geometry} material={materials['mat_0036_decals_c.003']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_37004.geometry} material={materials['plastic.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_38004.geometry} material={materials['mat_0038_warnings_c.003']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_39004.geometry} material={materials['plastic.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_4023.geometry} material={materials['plastic.009']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_40004.geometry} material={materials['plastic.009']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_41004.geometry} material={materials['mat_0041_dashboard.003']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_42003.geometry} material={materials['mat_0042_rubber_base.003']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_43003.geometry} material={materials['mat_0043_black_0.003']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_44003.geometry} material={materials['mat_0044_plastic_smooth.003']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_45003.geometry} material={materials['mat_0045_logo_c.003']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_5017.geometry} material={materials['plastic.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_6010.geometry} material={materials['plastic.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_7006.geometry} material={materials['mat_0007_roof_fabric_c.003']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_8006.geometry} material={materials['plastic.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.piece_9005.geometry} material={materials['plastic.008']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.Engine_Cover001.geometry} material={materials.engine} position={[0, 1.086, 3.017]} scale={0.915} />
      <mesh geometry={nodes.Car_battery001.geometry} material={materials.battery} position={[0.816, 0.469, 1.521]} scale={0.106} />
      <mesh geometry={nodes.Car_battery002.geometry} material={materials.battery} position={[0.816, 0.469, 2.015]} scale={0.106} />
      <mesh geometry={nodes.Car_battery003.geometry} material={materials.battery} position={[0.816, 0.469, 1.766]} scale={0.106} />
      <mesh geometry={nodes.Car_battery.geometry} material={materials.battery} position={[0.816, 0.469, 1.273]} scale={0.106} />
    </group>
  )
}

useGLTF.preload('/KenworthTest.glb')
